### ISSUE TITLE
No module named 'biscuit.cli'

### ISSUE THREAD

**Issue by tomlin7** [tomlin7/biscuit#464]
### Discussed in https://github.com/tomlin7/biscuit/discussions/461

<div type='discussions-op-text'>

<sup>Originally posted by **mkh-user** November 28, 2024</sup>
Hello, I was trying to install this editor but I encountered various errors.
I have previously installed Python 3.11, Git, pip, and so on.
I have tried these two methods:
1. from pip
Currently, when I use `pip install biscuit-editor`, everything is fine and it installs successfully, but when I use `biscuit` to run the program:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python311\Scripts\biscuit.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'biscuit.cli'
```
2. from releses
I downloaded and ran the latest version, but it encounters these errors and closes:
![image](https://github.com/user-attachments/assets/2c5d1d73-e2fd-436e-8e79-48b51d744fc5)

(All in Windows10 X64)</div>

**Comment by tomlin7** [comment]
@mkh-user thanks for pointing out the bug! the logo was used within empty editor area placeholder. But is no longer used in new design. This bug is resolved in the latest `v3.0.1`

try
```
pip install --upgrade biscuit-editor
biscuit
```
